bf16: false
dataloader_num_workers: 1
dataset_name: seniichev/amazon-fashion-2023-full
early_stopping_min_delta: 0.001
early_stopping_patience: 0
eval_steps: 0
evaluation_strategy: 'no'
fp16: false
fusion_dim: 1024
gradient_accumulation_steps: 16
gradient_checkpointing: true
id_dim: 512
id_vocab_size: 709036
item_id_field: parent_asin
learning_rate: 1e-5
load_best_model_at_end: false
log_file: logs/semantic_recommendation_safe.log
logging_steps: 5
max_grad_norm: 0.5
max_history_length: 10
metric_for_best_model: loss
min_history_length: 2
model_name_or_path: Qwen/Qwen2.5-Omni-7B
model_type: semantic_recommendation
num_train_epochs: 1
output_dir: ./output/semantic_recommendation_model_safe
per_device_train_batch_size: 8
reduced_dim: 1024
remove_unused_columns: false
report_to: wandb
run_name: semantic_recommendation_safe
save_steps: 1000
save_total_limit: 5
seed: 42
title_field: title
use_semantic_ids: true
user_id_field: user_id
vq_codebook_dim: 256
vq_codebook_size: 10000
warmup_steps: 200
